### ISSUE TITLE
I can't install on Latest Laravel 8 (v8.80.0)

### ISSUE THREAD

**Issue by harshpatel147** [eduardostuart/face#15]
when I'm trying to install this package using **composer require eduardostuart/face** command then its show error about dependencies versions 

```
Problem 1
    - Root composer.json requires eduardostuart/face ^2.0 -> satisfiable by eduardostuart/face[v2.0.0].
    - eduardostuart/face v2.0.0 requires guzzlehttp/guzzle ^6.3 -> found guzzlehttp/guzzle[6.3.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

it tell me to downgrade the guzzleHttp package version. but I won't to downgrade. because its depends on _psr7_  & that guzzleHttp & psr7 is becomes by default with fresh Laravel 8 installation.

So, Please I request to you. please add supporting version for Latest Laravel 8

**Comment by eduardostuart** [comment]
Hi @harshpatel147, 

Sorry, but this package is not maintained anymore. 

If you still want to use it, feel free to fork and update these entires on composer.json: 

```
"guzzlehttp/guzzle": "^6.*|7.*",
"illuminate/support": "5.*|7.*|8.*|9.*"
```
