### ISSUE TITLE
Authentication error,Configured correctly

### ISSUE THREAD

**Issue by wenber-yu** [eduardostuart/face#2]
Client error: `POST https://api-us.faceplusplus.com/facepp/v3/detect` resulted in a `401 Unauthorized` response:
{"error_message":"AUTHENTICATION_ERROR"}

With the same configuration, an official example is ok

**Comment by eduardostuart** [comment]
Hi @ziyanziyu,

Everything is working as expected.

Did you set the Face++ (https://www.faceplusplus.com/)  secret and key  in your .env file ?


![Image](http://share.s.tuart.me/Uenbwc/3wFeoi3b+)
