### ISSUE TITLE
Compare API

### ISSUE THREAD

**Issue by herryswastika** [eduardostuart/face#8]
Hi, thanks for your package. Just a simple question, how do I compare two faces, one face from database, another taken from webcam ? is there specific command? The nearest command is Search API, but reading from Face++ Doc, the Compare API will return percentage and threshold. So my idea is the threshold is Admin's preference.
Thanks

**Comment by eduardostuart** [comment]
Hi @herryswastika , 

Yes, on Face++ you can use Compare Api. I still need to implement that. For now, the only thing possible with face package is using the search api, sorry about that.

Feel free to send a PR - that would be awesome :)
